version: "3.7"
networks:
  network:
    driver: bridge

services:
  mysql-database:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - network
  
  rabbitmq:
    image: rabbitmq:3.8.14-management
    networks:
      - network
    ports:
      - 5672:5672
      - 15672:15672
      
  transacoes-api:
    image: transacoes-api/app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app
    env_file:
      - .env
    networks:
      - network
    depends_on:
      mysql-database:
        condition: service_healthy
    depends_on:
      - rabbitmq
    links:
      - rabbitmq